workflows:
  version: 2
  build-dev: # ignore all normal git branches (untagged)
    jobs:
      - build:
          filters:
            branches:
              only: /^develop.*/
            tags:
              ignore: /.*/
      - get-live-credentials:
          requires: 
            - build
      - deploy-dev:
          requires: 
            - get-live-credentials
  build-live: # ignore all normal git branches (untagged)
    jobs:
      - build:
          filters:
            branches:
              only: /master/
            tags:
              ignore: /.*/
      - get-live-credentials:
          requires: 
            - build
      - deploy-live:
          requires: 
            - get-live-credentials


version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-26-ndk-r17b
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout # checkout source codes
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          paths:
            - ~/.gradle
  
  get-live-credentials:
    steps:
      - run:
          name: 'Preparing for APK Signing if necessary'
          command: |
              # download keystore when building live version
              curl -L -o release.keystore "${KEYSTORE_URL}"
              curl -L -o gradle.properties "${GRADLE_PROP_URL}"
      - persist_to_workspace:
          root: ~/app
          paths:
            - live.jks
            - gradle.properties

  deploy-dev:
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: 'Deploying to Deploygate'
          command: |
              echo 'Deploying to DeployGate'
              ./gradlew assembleDebug
  
  deploy-live:
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: 'Deploying to Playstore'
          command: |
              echo 'Deploying to Playstore'
              ./gradlew assembleRelease
      
                