version: 2
jobs:
  build:
    working_directory: ~/calabash-test
    docker:
      # - image: gusterveltra/calabash-test:0.0.1
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - run: npm -v
      - run: sudo npm install -g appcenter-cli
      - run: appcenter help
      - run: bundle install
      - run: ./gradlew assembleDebug
      - run: ./appcenter-post-build.sh