version: 2
jobs:
  build:
    docker:
      # - image: gusterveltra/calabash-test:0.0.1
      - image: circleci/android:api-26-alpha
      # - image: menny/android_ndk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: echo $ANDROID_HOME

      # - run: gem install bundler
      # - run: bundle update
      # - run: gem search json --local
      
      - run: sdkmanager --list --verbose | grep system-images
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n device1 -k "system-images;android-24;default;armeabi-v7a"
      # - run:
      #     name: Launch emulator
      #     command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd device1 -noaudio -no-boot-anim -no-window -accel on
      #     background: false
      
      - run:
          name: Validating AVD
          command: emulator -list-avds
      - run:
          name: 'Starting Android Emulator:'
          command: emulator -avd device1 -no-audio -no-window
      - run: circle-android wait-for-boot
      - run:
          name: Unlock the emulator
          command: adb shell input keyevent 82

      - run: keytool -genkey -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
      - run: calabash-android run app/build/outputs/apk/app-debug.apk