version: 2
jobs:
  build:
    working_directory: ~/calabash-test
    docker:
      # - image: gusterveltra/calabash-test:0.0.1
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - run: npm install -g appcenter-cli
      - run: appcenter help